apiVersion: v1
kind: Namespace
metadata:
  name:  ns-posthub--env--
  labels:
    name: ns-posthub--env--

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments--env--
  namespace: ns-posthub--env--
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments--env--
  template:
    metadata:
      labels:
        app: comments--env--
    spec:
      containers:
      - name: comments--env--
        image: __ImageTag__
        env:
        - name: MONGO_URI
          value: mongodb://comments-mongo-service:27020/comments
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: jwtsecret
              key: JWTKEY
        - name: NATS_CLUSTER_ID
          value: posthubcluster
        - name: NATS_CLIENT_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NATS_URL
          value: 'http://nats-eventhub-service:4222'
        resources:
          requests:
              cpu: 250m
              memory: 350Mi
          limits:
            memory: "900Mi"
            cpu: "700m"
        readinessProbe:
          httpGet:
            path: /api/comments/healthcheck
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
        - containerPort: 3000



---
kind: Service
apiVersion: v1
metadata:
  name:  comments-service--env--
  namespace: ns-posthub--env--
spec:
  selector:
    app:  comments--env--
  type:  ClusterIP
  ports:
  - name:  comments--env--
    port:  3000
    targetPort:  3000
    protocol:  TCP