apiVersion: 
kind: Deployment
metadata:
  name: hello-world-rest-api-v1
  labels:
    app: hello-world-rest-api
    version: v1
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: hello-world-rest-api
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 24%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world-rest-api
        version: v1
    spec:
      containers:
      - image: caesarsage/hello-world-rest-api:0.0.4-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: hello-world-rest-api-v1
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default
spec:
  selector:
    app: hello-world-rest-api
  ports:
  - nodePort: 30702
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
    